name = "App"
uuid = "d128dbd7-c220-4b47-8215-94b2c1b98d91"
authors = ["Korbinian Eckstein <korbinian90@gmail.com>"]
version = "4.0.6"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CLEARSWI = "06ae4d9b-ce5e-4813-a1b3-426e46312ec2"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
QSM = "794fc106-2fa4-440f-961c-0d7d7b47016a"
ROMEO = "1ea8258b-a15d-4adb-ad20-01632f467a84"

[compat]
ArgParse = "1"
CLEARSWI = "1.3"
MriResearchTools = "3.1"
QSM = "0.5.4"
ROMEO = "1"
julia = "1.9"
